import Link from 'next/link';
import { Metadata } from 'next';
import { AmazonAffiliateProducts } from '@/components/AmazonAffiliateProducts';

export const metadata: Metadata = {
  title: 'Terms of Service | Parent Schedule',
  description: 'Terms of Service for the Parent Schedule application.',
};

export default function TermsOfService() {
  return (
    <div className="bg-white min-h-screen pt-24 pb-16">
      <div className="container mx-auto px-4 sm:px-6 lg:px-8 max-w-4xl">
        <h1 className="text-4xl font-extrabold text-gray-900 mb-8 tracking-tight">Terms of Service</h1>
        <div className="prose prose-indigo max-w-none text-gray-700 space-y-6">
          <p className="text-sm text-gray-500">Last updated: {new Date().toLocaleDateString()}</p>
          
          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">1. Agreement to Terms</h2>
          <p>
            By accessing or using the Parent Schedule application ("Service"), you agree to be bound by these Terms of Service. 
            If you disagree with any part of the terms, then you may not access the Service.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">2. Description of Service</h2>
          <p>
            Parent Schedule is an advanced co-parenting calendar and rules engine designed to help divorced or separated parents track custody rotations and exceptions. 
            The Service provides scheduling tools mathematically based on the input values provided by the users.
          </p>

          <div className="bg-amber-50 border-l-4 border-amber-500 p-4 my-6">
            <h3 className="text-sm font-bold text-amber-800 m-0 pb-1">Not Legal Advice Disclaimer</h3>
            <p className="text-sm text-amber-700 m-0">
              The calculations, schedules, and algorithms generated by Parent Schedule are intended purely as organizational tools. 
              <strong> The Service does not constitute legal advice and cannot replace an official court order. </strong>
              In the event of a discrepancy between the Service's generated outputs and a legally binding court order, the court order always takes legal precedence. 
              Always consult with a qualified family law attorney regarding custody disputes.
            </p>
          </div>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">3. User Accounts</h2>
          <ul className="list-disc pl-6 space-y-2">
            <li>When you create an account with us, you must provide accurate, complete, and current information at all times.</li>
            <li>You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.</li>
            <li>You agree not to disclose your password to any third party. You must notify us immediately upon becoming aware of any breach of security or unauthorized use of your account.</li>
          </ul>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">4. Affiliate Advertising</h2>
          <p>
            The Service may display advertisements or affiliate links (including the Amazon Services LLC Associates Program). 
            We may earn a commission from purchases made through these links at no additional cost to you. 
            We do not endorse or take responsibility for the products, services, or privacy practices of third-party websites accessed via these links.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">5. Intellectual Property</h2>
          <p>
            The Service and its original content, features, and functionality are and will remain the exclusive property of Parent Schedule and its licensors. 
            The Service is protected by copyright, trademark, and other laws of both the United Kingdom and foreign countries.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">6. "AS IS" Software & Disclaimer of Warranties</h2>
          <p>
            Because Parent Schedule is provided completely free of charge, the Service is provided to you "AS IS" and "AS AVAILABLE" and with all faults and defects without warranty of any kind. 
            To the maximum extent permitted under applicable law, we expressly disclaim all warranties, whether express, implied, statutory or otherwise, with respect to the Service, including all implied warranties of merchantability, fitness for a particular purpose, title and non-infringement. 
            We make no representation or warranty that the Service will meet your requirements, achieve any intended results, operate without interruption, meet any performance or reliability standards, or be error-free.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">7. Complete Release of Liability</h2>
          <p>
            You explicitly acknowledge and agree that because the Service is provided for free, we accept <strong>absolutely zero responsibility</strong> for any issues, damages, or disputes that arise from your use of the Service.
            In no event shall Parent Schedule, nor its operator, developer, or affiliates, be liable for any personal, indirect, incidental, special, consequential or punitive damages, including without limitation:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Custody violations, missed time, or scheduling miscalculations arising from software usage.</li>
            <li>Loss of data, loss of goodwill, or other intangible losses.</li>
            <li>Any conduct or content of any third party using the Service.</li>
          </ul>
          <p>
            Your ultimate remedy for dissatisfaction with the Service is simply to stop using it. By continuing to use this free software, you waive any right to legally hold the developer or platform accountable for any consequences.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">8. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. 
            Upon termination, your right to use the Service will immediately cease.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">8. Changes to Terms</h2>
          <p>
            We reserve the right, at our sole discretion, to modify or replace these Terms at any time. 
            If a revision is material we will try to provide at least 30 days notice prior to any new terms taking effect. 
            What constitutes a material change will be determined at our sole discretion.
          </p>

          <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">Contact Us</h2>
          <p>
            If you have any questions about these Terms, please contact us via the <Link href="/contact" className="text-indigo-600 hover:underline">Contact page</Link>.
          </p>
        </div>
        
        <div className="mt-16 pt-12 border-t border-gray-100">
          <AmazonAffiliateProducts variant="grid" title="Recommended Gear" maxProducts={3} />
        </div>
      </div>
    </div>
  );
}
